#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Increase upload limits for local development.
@ini_set('upload_max_filesize', '20M');
@ini_set('post_max_size', '20M');
@ini_set('max_input_time', '300');
@ini_set('max_execution_time', '300');

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
